source-item-ordering = []
module-item-order-groupings = [
    [
        "modules",
        [
            "extern_crate",
            "mod",
            "foreign_mod",
        ],
    ],
    [
        "use",
        [
            "use",
        ],
    ],
    [
        "macros",
        [
            "macro",
        ],
    ],
    [
        "global_asm",
        [
            "global_asm",
        ],
    ],
    [
        "UPPER_SNAKE_CASE",
        [
            "static",
            "const",
        ],
    ],
    [
        "Aliases",
        [
            "ty_alias",
            "trait_alias",
        ],
    ],
    [
        "Traits",
        [
            "trait",
        ],
    ],
    [
        "structs_enums_and_impls",
        [

            "struct",
            "enum",
            "impl",
            "union",
        ],

    ],
    [
        "lower_snake_case",
        [
            "fn",
        ],
    ],
]
