[package]
name = "palette-mapper-macros"
edition.workspace = true
version.workspace = true

[dependencies]
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = "2.0.114"

[lints]
workspace = true

[lib]
proc-macro = true
